const { play } = require('../src/mcts/newMain');

describe('run a simulation of a turn', () => {
    it('board empty, 8 cards, 12 mana', () => {
        const gameState = {
            phase: 'play',
            player: {
                health: 28,
                mana: 3,
                deck: 23,
                rune: 25,
                draw: 1,
            },
            opponent: {
                health: 30,
                mana: 2,
                deck: 23,
                rune: 25,
                draw: 1,
                hand: 5,
                oppActions: [
                    '7 ATTACK 4 -1',
                    '6 SUMMON 12',
                ],
            },
            hand: [
                {
                    number: 139,
                    id: 13,
                    location: 0,
                    type: 'greenItem',
                    ccm: 4,
                    power: 0,
                    toughness: 0,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: true,
                    ward: true,
                    cardDraw: 0,
                },
                {
                    number: 88,
                    id: 9,
                    location: 0,
                    type: 'creature',
                    ccm: 5,
                    power: 4,
                    toughness: 4,
                    breakthrough: false,
                    charge: true,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 97,
                    id: 7,
                    location: 0,
                    type: 'creature',
                    ccm: 3,
                    power: 3,
                    toughness: 3,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: true,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 74,
                    id: 5,
                    location: 0,
                    type: 'creature',
                    ccm: 5,
                    power: 5,
                    toughness: 4,
                    breakthrough: true,
                    charge: false,
                    drain: false,
                    guard: true,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 6,
                    id: 3,
                    location: 0,
                    type: 'creature',
                    ccm: 2,
                    power: 3,
                    toughness: 2,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 76,
                    id: 1,
                    location: 0,
                    type: 'creature',
                    ccm: 6,
                    power: 5,
                    toughness: 5,
                    breakthrough: true,
                    charge: false,
                    drain: true,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
            ],
            myBoard: [
                {
                    number: 7,
                    id: 11,
                    location: 1,
                    type: 'creature',
                    ccm: 2,
                    power: 2,
                    toughness: 2,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: true,
                    cardDraw: 0,
                },
            ],
            oppBoard: [
                {
                    number: 6,
                    id: 12,
                    location: -1,
                    type: 'creature',
                    ccm: 2,
                    power: 3,
                    toughness: 2,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 7,
                    id: 4,
                    location: -1,
                    type: 'creature',
                    ccm: 2,
                    power: 2,
                    toughness: 2,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: true,
                    cardDraw: 0,
                },
            ],
        };
        const t1 = performance.now();
        const set = play(gameState);
        const t2 = performance.now();
        const time = t2 - t1;
        expect(time).toBeGreaterThan(10);
    });
});
