const { play } = require('../src/mcts/newMain');

describe('run a simulation of a turn', () => {
    it('board empty, 8 cards, 12 mana', () => {
        const gameState = {
            phase: 'play',
            player: {
                health: 30,
                mana: 7,
                deck: 19,
                rune: 25,
                draw: 1,
            },
            opponent: {
                health: 28,
                mana: 6,
                deck: 19,
                rune: 25,
                draw: 1,
                hand: 6,
                oppActions: [
                    '109 SUMMON 10',
                ],
            },
            hand: [
                {
                    number: 61,
                    id: 21,
                    location: 0,
                    type: 'creature',
                    ccm: 9,
                    power: 10,
                    toughness: 10,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 109,
                    id: 19,
                    location: 0,
                    type: 'creature',
                    ccm: 5,
                    power: 5,
                    toughness: 6,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 22,
                    id: 15,
                    location: 0,
                    type: 'creature',
                    ccm: 6,
                    power: 7,
                    toughness: 5,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 16,
                    id: 11,
                    location: 0,
                    type: 'creature',
                    ccm: 4,
                    power: 6,
                    toughness: 2,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
            ],
            myBoard: [
                {
                    number: 18,
                    id: 17,
                    location: 1,
                    type: 'creature',
                    ccm: 4,
                    power: 7,
                    toughness: 4,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
                {
                    number: 5,
                    id: 13,
                    location: 1,
                    type: 'creature',
                    ccm: 2,
                    power: 4,
                    toughness: 1,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
            ],
            oppBoard: [
                {
                    number: 109,
                    id: 10,
                    location: -1,
                    type: 'creature',
                    ccm: 5,
                    power: 5,
                    toughness: 6,
                    breakthrough: false,
                    charge: false,
                    drain: false,
                    guard: false,
                    lethal: false,
                    ward: false,
                    cardDraw: 0,
                },
            ],
        };
        const t1 = performance.now();
        const set = play(gameState);
        const t2 = performance.now();
        const time = t2 - t1;
        expect(time).toBeGreaterThan(10);
    });
});
